# Generated by Django 5.1.3 on 2024-12-07 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_remove_user_preferred_genres_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='spotify_url',
            new_name='youtube_url',
        ),
    ]
