# Generated by Django 5.1.3 on 2024-12-07 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_rename_user_to_profile'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usersong',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='usersong',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='usersong',
            name='song',
        ),
        migrations.AlterField(
            model_name='shownprofile',
            name='shown_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shown_to_profiles', to='project.profile'),
        ),
        migrations.CreateModel(
            name='ProfileGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_genres', to='project.genre')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_genres', to='project.profile')),
            ],
            options={
                'unique_together': {('profile', 'genre')},
            },
        ),
        migrations.CreateModel(
            name='ProfileSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_songs', to='project.profile')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_songs', to='project.song')),
            ],
            options={
                'unique_together': {('profile', 'song')},
            },
        ),
        migrations.DeleteModel(
            name='UserGenre',
        ),
        migrations.DeleteModel(
            name='UserSong',
        ),
    ]
