# Generated by Django 5.1.3 on 2024-12-09 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_profile_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
